#!/usr/bin/python                                                                                                     

import multiprocessing
from subprocess import *
import sys
import os
import time
import socket

def worker(num):
    """thread worker function"""
    node=("pkbe-gpu%d")%num
    for j in range(1,3):
        myip = "10.17." + str(num) + "." + str(j)
        chkstr = ["ssh", "-o","ConnectTimeout=3",node, "/home/mal171/paf/tools/fpga_test ", myip]
        output =  Popen(chkstr, bufsize=1, stdout=PIPE, stderr=PIPE).communicate()
        sys.stderr.write(('%d %s')% (num, output[0]))
    
    return

if __name__ == '__main__':
   
    if socket.gethostname() != "pktos01":
        sys.stderr.write ("Command can be run only from pkstos01\n")
        sys.exit()

    jobs = []
    for i in range(2):
        p = multiprocessing.Process(target=worker, args=(i,))
        jobs.append(p)
        p.start()
        time.sleep(2)

    for p in jobs:
        p.join()
    print "...done"
